/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thitracnghiem;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Gum
 */
public class CLIENT_TRACNGHIEM extends javax.swing.JFrame {
JFileChooser c = new JFileChooser();

 ButtonGroup G = new ButtonGroup();
   String anw ;
   JButton jbnt =new JButton("click");  
    /**
     * Creates new form CLIENT_TRACNGHIEM
     */
    public CLIENT_TRACNGHIEM() {
        initComponents();
          
           G.add(jrbA);
             G.add(jrbB);
              G.add(jrbC);
              G.add(jrbD);
         
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCauhoi = new javax.swing.JLabel();
        jrbA = new javax.swing.JRadioButton();
        jrbB = new javax.swing.JRadioButton();
        jrbC = new javax.swing.JRadioButton();
        jrbD = new javax.swing.JRadioButton();
        btnNopbai = new javax.swing.JButton();
        btnTiep = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCauhoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCauhoi.setText("CÂU 1 : mạng man được sử dụng trong phạm vi:");

        jrbA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrbA.setText("A. QUỐC GIA");
        jrbA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAActionPerformed(evt);
            }
        });

        jrbB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrbB.setText("B. LỤC ĐỊA");

        jrbC.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrbC.setText("C. KHU PHỐ");

        jrbD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jrbD.setText("D. THÀNH PHỐ");

        btnNopbai.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNopbai.setText("NỘP BÀI");
        btnNopbai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNopbaiActionPerformed(evt);
            }
        });

        btnTiep.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnTiep.setText("TIẾP THEO");
        btnTiep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("BÀI TRẮC NGHIỆM");

        txtTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTime.setText("Time : 20 s");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jrbA, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .addComponent(jrbC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbB, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jrbD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(btnTiep)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCauhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNopbai)
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNopbai)
                        .addGap(18, 18, 18)
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCauhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnTiep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ThiTracNghiem(){
        
    }
    private void btnNopbaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNopbaiActionPerformed
         try {

            Socket socket = new Socket("localhost", 13334);
            DataInputStream dis = new DataInputStream(socket.getInputStream());
            DataOutputStream dos = new DataOutputStream(socket.getOutputStream());
            CauHoi CH = new CauHoi();
            String strTN = dis.readUTF();
            String[] arrStr = strTN.split("///");
            List<CauHoi> listCH = new ArrayList<CauHoi>();
            
            int i = 0;
            int dem = 0;
            for (i = 0; i < arrStr.length;) {
                if (dem < 10) {
                    CH = new CauHoi();
                    CH.setCauhoi(Integer.parseInt(arrStr[i]));
                    CH.setTrinhDo(arrStr[i + 1]);
                    CH.setNoiDung(arrStr[i + 2]);
                    CH.setCauA(arrStr[i + 3]);
                    CH.setCauB(arrStr[i + 4]);
                    CH.setCauC(arrStr[i + 5]);
                    CH.setCauD(arrStr[i + 6]);
                    CH.setDapAn(arrStr[i + 7]);
                    listCH.add(CH);
                    i = i + 8;
                }
                dem++;
            }
            dem = 0;
            String anwClient = "";
            boolean checkinput = true;
            for (CauHoi ch : listCH) {
                dem++;
                
                System.out.println(dem + ": " + ch.getNoiDung());
                txtCauhoi.setText(dem + ": " + ch.getNoiDung());
                System.out.println("A. " + ch.getCauA());
                jrbA.setText("A "+ ch.getCauA());
                System.out.println("B. " + ch.getCauB());
                 jrbB.setText("B. " + ch.getCauB());
                System.out.println("C. " + ch.getCauC());
                 jrbC.setText("C. " + ch.getCauC());
                System.out.println("D. " + ch.getCauD());
                 jrbD.setText("D. " + ch.getCauD());
               
                ActionListener actionListener = null;    
                jrbA.addActionListener(actionListener);
                jrbB.addActionListener(actionListener);
                jrbC.addActionListener(actionListener);
                jrbD.addActionListener(actionListener);
                add(jrbA);add(jrbB);add(jbnt);  add(jrbC);add(jrbD);

         if (jrbA.isSelected()) {
        
          
         btnTiep.addActionListener(new ActionListener() {
             @Override
             public void actionPerformed(ActionEvent e) {
                anw="A";
                
             }
         });
         add(btnTiep);anwClient += dem + "///";
          anwClient += anw + "///";
         continue;
        
//                        anwClient += dem + "///";
//                        anwClient += anw + "///";
//                        checkinput = false;
                }

         else if (jrbB.isSelected())
         {
                    anw = "B";
    
    
//                        anwClient += dem + "///";
//                        anwClient += anw + "///";
//                        checkinput = false;
                      
                    
       }
          else if (jrbC.isSelected())
         {
      anw = "C";
      
//                        anwClient += dem + "///";
//                        anwClient += anw + "///";
                       
                    
       }
          else if (jrbD.isSelected())
         {
       anw = "D";
//                        anwClient += dem + "///";
//                        anwClient += anw + "///";
                   
                       
                    
       }
                checkinput = true;
                  JButton jbnt =new JButton("click");   
                
       
    
                while (checkinput) {
                  
                    if (anw.equals("A") || anw.equals("B") || anw.equals("C") || anw.equals("D")) {
                        anwClient += dem + "///";
                        anwClient += anw + "///";
                        checkinput = false;
                    } else {
                        System.out.println("Nhap sai vui long nhap lai!");
                         JOptionPane.showMessageDialog(null,"VUI Long click vao 1 dap an truoc khi tra loi!");
                    }
                }
            }
            dos.writeUTF(anwClient);

            String answer = dis.readUTF();
            System.out.println(answer);

        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnNopbaiActionPerformed

    private void jrbAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAActionPerformed
        
    }//GEN-LAST:event_jrbAActionPerformed

    private void btnTiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepActionPerformed
           
        
    }//GEN-LAST:event_btnTiepActionPerformed

    
    /**
     * @param args the command line arguments
     */
   

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLIENT_TRACNGHIEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLIENT_TRACNGHIEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLIENT_TRACNGHIEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLIENT_TRACNGHIEM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new CLIENT_TRACNGHIEM().setVisible(true);
             
            }
               
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNopbai;
    private javax.swing.JButton btnTiep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jrbA;
    private javax.swing.JRadioButton jrbB;
    private javax.swing.JRadioButton jrbC;
    private javax.swing.JRadioButton jrbD;
    private javax.swing.JLabel txtCauhoi;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
