/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thitracnghiem;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gum
 */
public class KETQUA extends javax.swing.JFrame {

    /**
     * Creates new form KETQUA
     */
    Vector vctHeader = new Vector();
    Vector vctData = new Vector();
    public KETQUA() {
        initComponents();
        vctHeader.add("Mã");
        vctHeader.add("Câu Hỏi");
        vctHeader.add("ĐA của bạn");
        vctHeader.add("Đ/a Đúng");
        
        Vector vctRow1 = new Vector();
        vctRow1.add("1");
        vctRow1.add("Câu 1");
        vctRow1.add("A");
        vctRow1.add("A");
       vctData.add(vctRow1);
         Vector vctRow2 = new Vector();
        vctRow1.add("2");
        vctRow1.add("Câu 2");
        vctRow1.add("A");
        vctRow1.add("B");
        vctData.add(vctRow2);
         Vector vctRow3 = new Vector();
        vctRow1.add("3");
        vctRow1.add("Câu 3");
        vctRow1.add("A");
        vctRow1.add("C");
        vctData.add(vctRow3);
         Vector vctRow4 = new Vector();
        vctRow1.add("4");
        vctRow1.add("Câu 4");
        vctRow1.add("A");
        vctRow1.add("D");
        vctData.add(vctRow4);
         Vector vctRow5 = new Vector();
        vctRow1.add("5");
        vctRow1.add("Câu 5");
        vctRow1.add("A");
        vctRow1.add("A");
       vctData.add(vctRow5);
         Vector vctRow6 = new Vector();
        vctRow1.add("6");
        vctRow1.add("Câu 6");
        vctRow1.add("A");
        vctRow1.add("C");
        vctData.add(vctRow6);
         Vector vctRow7 = new Vector();
        vctRow1.add("7");
        vctRow1.add("Câu 7");
        vctRow1.add("A");
        vctRow1.add("A");
       vctData.add(vctRow7);
         Vector vctRow8 = new Vector();
        vctRow1.add("8");
        vctRow1.add("Câu 9");
        vctRow1.add("A");
        vctRow1.add("B");
        vctData.add(vctRow8);
         Vector vctRow9 = new Vector();
        vctRow1.add("9");
        vctRow1.add("Câu 9");
        vctRow1.add("A");
        vctRow1.add("C");
       vctData.add(vctRow9);
         Vector vctRow10 = new Vector();
        vctRow1.add("10");
        vctRow1.add("Câu 10");
        vctRow1.add("A");
        vctRow1.add("D");
        vctData.add(vctRow10);
        
        jTableKetqua.setModel(new DefaultTableModel(vctData,vctHeader));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKetqua = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableKetqua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÂU HỎI", "ĐÁP ÁN CỦA BẠN", "ĐÁP ÁN ĐÚNG"
            }
        ));
        jScrollPane1.setViewportView(jTableKetqua);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("ĐIỂM : 3");

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setText("KẾT QUẢ");

        jButton1.setText("THOÁT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(264, 264, 264)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(298, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(342, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KETQUA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KETQUA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KETQUA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KETQUA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KETQUA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKetqua;
    // End of variables declaration//GEN-END:variables
}
